pipeline {
   agent any

   stages {
      stage('checkout') {
         steps {
            checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/Kapileson/contract-testing-boilerplate']]])
         }
      }
      
      stage('Npm Install') {
         steps {
             sh 'npm install'
        }   
      }
      
      stage('Run Consumer Test') {
         steps {
             sh 'npm run consumer-pact'
        }
      }
      
      stage('Publish Pact to Pact Broker') {
         steps {
             sh 'npm run publish-pact'
        }
      }

      stage('Deploy') {
         steps {
            sh 'npm run can-i-deploy'
         }
      }
   }
   
   
}
